# Generated by Django 4.0.3 on 2022-03-31 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('image', models.FileField(upload_to='static/images')),
                ('title', models.CharField(max_length=70)),
                ('id_field', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
                ('title', models.CharField(max_length=70)),
                ('image', models.FileField(upload_to='static/images')),
                ('id_field', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Super Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.FileField(upload_to='static/images')),
                ('id_field', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ManyToManyField(to='prometheus.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='supercategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prometheus.supercategory'),
        ),
    ]
